### ISSUE TITLE
Enhancement: panic in analyzer.go:paramsAsMap

### ISSUE THREAD

**Issue by fredbi** [go-openapi/analysis#22]
When extensively testing invalid specs with go-openapi/validate,
I realized the validator had to really control when and how calling the analyzer method (ParamsForOperation()) by anticipating problems. This is a complex and error prone process.

Particularly, func paramsAsMap() which is called by other methods, is quite intelorant to $ref errors (panics).

How about simply ignoring the error? or returning an error ?

**Comment by fredbi** [comment]
I am thinking of someting like:

```golang
func (s *Spec) paramsAsMap(parameters []spec.Parameter, res map[string]spec.Parameter) {
	for _, param := range parameters {
		pr := param
		if pr.Ref.String() != "" {
			obj, _, err := pr.Ref.GetPointer().Get(s.spec)
			if err != nil {
				// panic(err)
                                // Can't resolve $ref: skip
                               continue
			}
			if prAsParam, ok := obj.(spec.Parameter) ; ok {
                                  pr = prAsParam
                        } else {
                               // $ref resolved to another type: skip
                               continue
                        }
		}
		res[mapKeyFromParam(&pr)] = pr
	}
}

```

**Comment by fredbi** [comment]
Thus the semantics of, for instance, ParametersFor(), or ParamsFor() would become: 
"get all *valid* params" rather than "get all params" (implied: or panic if one is invalid).

**Comment by casualjim** [comment]
if you change the meaning of that's dangerous.

**Comment by fredbi** [comment]
please explain. I find dangerous too to get no guarantee that nothing is invalid...
In my current validate branch I had to go to some lengths to track and avoid this panic case.

**Comment by fredbi** [comment]
On the other hand, if we resort to proper error handling, we lose the elegant style for `p:= range ParametersFor() {...`.

**Comment by casualjim** [comment]
for invalid cases right? valid cases all work.

the panic here is for programmer error. It should definitely not continue on failure or ignore invalid cases. Because that's just kicking the can down the road.

**Comment by fredbi** [comment]
It is not a programmer error. The $ref case is obvious. The other one (from issue go-swagger/go-swagger#342 if I remember well) is a $ref sibling which overrides the parameter definition with a schema.

**Comment by fredbi** [comment]
It is all about *validating* the spec, not programmer's error

**Comment by fredbi** [comment]
i can live with that, though. I am just asking because what I've done in the validation code is not pretty: figuring out everything before calling the method and using a lot of safeguards just to turn around the panic()

**Comment by fredbi** [comment]
if you look at #342, the bug is fixed precisely because we stop before.
If I'd like to continue validating no matter what, bing, panic.

**Comment by casualjim** [comment]
we can provide a non-panicing method which does the proper error pattern. And re-implement the current method in terms of that. I don't want to preclude from making things better I just don't want to change behavior that existed for 2+ years. Because continue on error is a pretty fundamental change for an orthogonal case to the original intent which is build up routes and so on for serving.

**Comment by fredbi** [comment]
I admit it is.
But it is important too. I precisely invested several days on that because my patience stepping one error after another in huge specs was exhausted...
In the example above, the panic() is "just" to blank spaces away from the correct one. How frustrating ..

So you'd be in favor of loading additional "safe" methods, right?
Like: SafeParamsFor() ?

The paramsAsMap() is private, so it is easier to change it with error reporting.

I would prefer the single value return to still benefit from the range operator.

**Comment by fredbi** [comment]
and moving the panic() from paramsAsMap() to the calling interface methods in analysis.
Yes. Could be done.

**Comment by casualjim** [comment]
I think there are 2 major use callers for this. The validator would benefit from the proper error pattern. The spec should be valid before you generate so the panic doesn't hurt there and gives you a nicer experience

**Comment by fredbi** [comment]
OK let's do that.
Since this does change the existing interface, I'll make use of this new "safe" interface in another version of validate (the current pending PR is already more than loaded).

**Comment by casualjim** [comment]
yes adding without changing existing behavior is all fine by me.

**Comment by fredbi** [comment]
good. I'll do that on Friday.

**Comment by fredbi** [comment]
Thanks @casualjim
