### ISSUE TITLE
Head broken, ExpandSchemaWithBasePath

### ISSUE THREAD

**Issue by jayunit100** [go-openapi/analysis#26]
```
f59a71f0ece6f9dfb
```

```
../../vendor/github.com/go-openapi/analysis/flatten.go:587:42: not enough arguments in call to spec.ExpandSchemaWithBasePath
	have (*spec.Schema, nil, *spec.ExpandOptions)
	want (*spec.Schema, interface {}, spec.ResolutionCache, *spec.ExpandOptions)
```

**Comment by jayunit100** [comment]
Looks like https://github.com/go-openapi/analysis/blame/master/flatten.go#L587 wants more args.  Not sure what the right ones would be though ~

**Comment by fredbi** [comment]
You may find a live example of flatten usage [here](https://github.com/go-swagger/go-swagger/blob/f552963ac0dfdec0450f6749aeeeeb2d31cd5544/generator/shared.go#L939)

**Comment by mxinden** [comment]
@jayunit100 I have hit the same issue. The signature of the function `ExpandSchemaWithBasePath` in `github.com/go-openapi/spec` has changed. Make sure to use `github.com/go-openapi/analysis` with a recent version of `github.com/go-openapi/spec`.

**Comment by fredbi** [comment]
I hope we get go-openapi repos tagged in line with go-swagger releases soon. That would definitely prevent this kind of recurring issue.

**Comment by fredbi** [comment]
this is done for all go-openapi repos since 0.15. This should solve any temporary discrepancies when maintaining go-openap repos.

**Comment by mxinden** [comment]
> this is done for all go-openapi repos since 0.15. This should solve any temporary discrepancies when maintaining go-openap repos.

@fredbi Thanks, this is very helpful.
