### ISSUE TITLE
undefined: loadOrFail

### ISSUE THREAD

**Issue by dncohen** [go-openapi/analysis#49]
`go test` fails with:

```
 github.com/go-openapi/analysis [github.com/go-openapi/analysis.test]
./fixer_test.go:28:8: undefined: loadOrFail
FAIL    github.com/go-openapi/analysis [build failed]
FAIL
```

**Comment by fredbi** [comment]
Cannot reproduce this: I pulled master and ran `go test` successfully.
Could you tell us more about your environment?

**Comment by dncohen** [comment]
I setup a clean GOPATH and also cannot reproduce.

I believe the problem was caused when I ran out of disk space in the middle of a `go get`.  Must have been right as this package was downloading.

Thanks for looking and sorry 'bout that!
