### ISSUE TITLE
Leaked token/hook URL?

### ISSUE THREAD

**Issue by uchi-mata** [go-openapi/analysis#51]
Hi,

I came across this file:
https://github.com/go-openapi/analysis/blob/master/appveyor.yml

It contains a Slack Webhook and auth token which both have the potential to be sensitive.

I thought I'd double-check whether they are and whether you want to [remove](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository) them :) 

Thanks & best,
Matthias

**Comment by fredbi** [comment]
Our slack token is not sensitive. Thanks for the heads-up.
