### ISSUE TITLE
Support URLs as base paths for schemas

### ISSUE THREAD

**Issue by mikhailshilkov** [go-openapi/analysis#57]
I'd love to analyze a schema which is stored at GitHub directly

```go
url := "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2020-04-01/publicIpAddress.json"
spec := analysis.New(swagger)
err = analysis.Flatten(analysis.FlattenOpts{Spec: spec, Expand: true, BasePath: url})
```

Currently, I get

```
open /mylocalpath/https:/raw.githubusercontent.com/Azure/azure-rest-api-specs/master/
specification/network/resource-manager/Microsoft.Network/stable/2020-04-01/network.json: 
no such file or directory
```

as it tries to resolve external schema definitions (which are stored on the same GitHub).

Are there fundamental limitations to do this?

**Comment by fredbi** [comment]
No this should work. It think the problem you are hitting here is the proper resolution of cyclic refs (on a remote location).
There are still open bugs with this on github.com/go-openapi/spec, where this resolution is carried out. This obviously impacts the analysis package.

**Comment by mikhailshilkov** [comment]
That's great to hear; then it's just the error message being very confusing.
