### ISSUE TITLE
Slack private token in the analysis repo

### ISSUE THREAD

**Issue by jedsalazar** [go-openapi/analysis#82]
A slack private token seemingly used for build notifications to a #bots channel has been found in the the analysis repo. It's base64 encoded but should probably be encrypted or set to a variable and the credential should be rotated
https://github.com/cilium/tetragon/blob/main/vendor/github.com/go-openapi/analysis/appveyor.yml#L27-L29

**Comment by vpnachev** [comment]
Duplicate of #51

**Comment by casualjim** [comment]
It doesn't matter, the chat room is public. Anybody can join, there is nothing there.
